# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99811c0ef4093ebe8cf60351183ab43490734d8b204f77f0013a864dc0b182c94d5bf68f8b0723fe6612d5ac7fdc27bc31608ad8d02399cf7a47a3732213430d

test:
  secret_key_base: ed716752b309e870fc03eb0e437234e33aab591547848822970ba1038cbb22e360a5cd8864a925e22ea7b8092cef0062986fd0d51339d60249359bbea0d4c915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
